os:
  - linux
  - osx

language: generic

env:
  matrix:
    - python=3.5  CONDA_PY=35  
    - python=3.6  CONDA_PY=36
    - python=3.7  CONDA_PY=37

  global:
    - secure: "gqilMG3Mh9nrLeshHDseErmBc8Jol63qmWkcQR2An4AGuiti0qFTNucGbytZ5MhY/jYCtJIjM5O2+Nrbm7mKgQohsNuS9LVANa2cTkvx7938bYPcSCN9d6LOqv1+PQ13FlcU8Lbol1wGz4rXBgUCxJ0Kp4ARQqTQKj/w/TOXsIuM69jUBiZuct2qwHw3BWhmSxHkUNoyU+a80vabXJlZTgWcmg+gM4sMivcOPi877jLGps5N2/hfXZNUvssA2d2qTGf1ZQK17G+X5qipmGp/IBOkDb6XiRkuftOHL86u4HSrUobxZyKeDf0viL72sgUSRH7aPIVQLbbTKitw8FDaaNVVrABtC9XMXccYhdjAnqGMoVeqyZPdtFwRJuTONHtAWPmXkZKxdzLuvGMaQZ9dRbaxcuY3nC+BAimS95ltrjJ6tGPcQlpSUKQYO1ivOKPU0ZOcP2/xVgIOCkCEhbNf7X2nUQtDtX/oAw2lPE7SWIjZESIr9NIWYHLKW7ao+4LRKJ29OC5+jGSe+N/+qQ55gnnfmtFewveE/2ohIzvs7Lhs6ucxfNnYJyyw3nTXuhHVT8bONGhEtxq4SBhqXN7s4Z0BgkCh0Pyas5EKZNKStJNT5tt2qxJZpCMUBnQelK6Sn1q1OshHqhVajZN6uz4PXJueGWNnSNkC9lteU0m71RM="
    - secure: "YJgSGFNbJCR4ALGV7XwjOlbaV//uYZGg8ARCiPeAnaTxF4Y6fP4k3OT+s0tyUTubJGbfltn3L6OEuekyHBS5tseuNuvcihubf/6TSY9ssolKLZKaEHBkHtKKCYdIiSxDvGq6AxqpiHx0ZYXR+vy3xPDVi4kldDYzfcwhMpf0VlI5u47Df5x8RaO37RfEIayfOHbLUtvJzWrbR+7yHlew9AaWorOthzgNNMxBYYqnqVKdztm8YXI/X0H6rcWcHS0TaeWWr1d3oewt9Opnm6LJnYyg6+kqiA23PEicMOf/iTb7K0pgkB3edDhM88GXBa5zSn0MqVW1bpcubWdHuqScF5bdRdZ+C03QdKxHRWCIjPTDFPf2Zwl0w/T8HNNmV9Lxd7dQVh1eaaSI6F23rNU7CiYgpSqFT+Ce1HRf9yifot2eOurb+YOf8XqzkN0/sioloGvA0BV4ToL73wxbGwqDEWN9n+iuxvUyMy48VmReeDr0GVDr/YGVCOfCCEkoGQ25IpBpHmVBlfA/0fGDfBInj3mi0pwI06XntKdZ+/x5WdVHRrH4RCutVhA9mPX/5l3NKV7LgcXGf2pi2tTppoL7olJBaJlwx1idF9YWQwmBFPTP1pIESRuujkmXPQG156bUVoFueQ9WjaXKSXKeZrsP4LXHTEUZVR1Peae/4btTJfs="

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then curl -L -o miniconda.sh http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh; fi
  - chmod 755 miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n ingeotec python=$python
  - source activate ingeotec  
  - conda install --yes pip
  - pip install coverage
  - pip install coveralls
  - conda config --append channels ingeotec  
  - conda install --yes numpy scipy scikit-learn nltk nose b4msa evodag conceptmodelling cython
  - python setup.py build_ext --inplace
  
script:
  - which python
  - python --version
  - which coverage
  - python -c "import nltk; nltk.download('stopwords')"
  - if [ $python = 3.6 ]; then coverage run setup.py nosetests; fi
  - if [ $python = 3.5 ]; then nosetests --verbose -exe EvoMSA; fi
  - if [ $python = 3.7 ]; then nosetests --verbose -exe EvoMSA; fi  

after_success:
  - if [ $python = 3.6 ]; then coveralls || echo "Coveralls upload failed"; fi
  - if [ $TRAVIS_BRANCH = "master" -a $python = 3.6 ]; then python setup.py sdist; pip install twine; twine upload -u mgraffg -p $TWINE dist/*.tar.gz; fi
  - if [ $TRAVIS_BRANCH = "master" ]; then python setup.py bdist_wheel; pip install twine; twine upload -u mgraffg -p $TWINE dist/*.whl; fi  
  - if [ $TRAVIS_BRANCH = "master" ]; then source deactivate; conda install --yes pip conda-build jinja2 anaconda-client; conda build conda-recipe --quiet; fi
  - python continuous-integration/move-conda-package.py conda-recipe  
  - which binstar
  - python continuous-integration/binstar-push.py

notifications:
    email:
      recipients:
        - mario.graff@infotec.mx
        - eric.tellez@infotec.mx
        - sabino.miranda@infotec.mx
        - dmoctezuma@centrogeo.edu.mx
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
