package:
  name: evomsa
  version: "0.13"

requirements:
  build:
    - python
    - setuptools
    - b4msa
    - evodag
    - scikit-learn
  run:
    - python
    - b4msa
    - evodag

test:
    requires:
        - nose
        - numpy
        - scipy
        - scikit-learn
        - gensim
        - nltk
        - b4msa
        - evodag
        - coverage

    imports:
        - EvoMSA

    commands:
        - nosetests --verbose -exe EvoMSA
        - EvoMSA-predict --help
        - EvoMSA-train --help


about:
  home: https://github.com/ingeotec/EvoMSA
  summary: Sentiment Analysis System based on B4MSA and EvoDAG.
  license: Apache
