package:
  name: evomsa
  version: "0.19"

requirements:
  build:
    - python
    - setuptools
    - b4msa
    - evodag
    - conceptmodelling
    - scikit-learn
  run:
    - python
    - b4msa
    - evodag
    - conceptmodelling

test:
    requires:
        - nose
        - numpy
        - scipy
        - scikit-learn
        - gensim
        - nltk
        - b4msa
        - evodag
        - conceptmodelling
        - coverage

    imports:
        - EvoMSA

    commands:
        - python -c "import nltk; nltk.download('stopwords')"      
        - nosetests --verbose -exe EvoMSA
        - EvoMSA-predict --help
        - EvoMSA-train --help


about:
  home: https://github.com/ingeotec/EvoMSA
  summary: Sentiment Analysis System based on B4MSA and EvoDAG.
  license: Apache
