name: Conda

on: 
  push:
    branches:
      - master   

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]	
        python-version: ["3.7", "3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge, ingeotec
        allow-softlinks: true
        channel-priority: flexible
        show-channel-urls: true	
    - name: Install dependencies
      run: |
        conda install --yes pip conda-build jinja2 anaconda-client
        conda install --yes numpy scipy scikit-learn nltk nose b4msa evodag conceptmodelling cython
        python -c "import nltk; nltk.download('stopwords')"
    - name: conda
      env:
        ANACONDA: ${{ secrets.ANACONDA }}
      run: |
        conda build conda-recipe --quiet	
        python continuous-integration/move-conda-package.py conda-recipe
        python continuous-integration/binstar-push.py