name: Tests

on: 
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}      
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: test
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        allow-softlinks: true
        channel-priority: flexible
        show-channel-urls: true	
    - name: Install dependencies
      run: |
        conda install --yes pip
        pip install coverage
        pip install coveralls
        conda install --yes numpy scipy scikit-learn nltk pytest b4msa evodag cython IngeoML>=0.0.25
        pip install jax
        pip install optax        
        python -c "import nltk; nltk.download('stopwords')"
        python setup.py build_ext --inplace
    - name: Tests on Linux
      if: ${{ runner.os == 'Linux' }}
      run: |
        which python
        python --version
        which coverage
        coverage run -m pytest EvoMSA/tests
    - name: Tests on macOS and Windows
      if: ${{ runner.os != 'Linux' }}
      run: |
        python -m pytest EvoMSA/tests
    - name: coveralls
      if: ${{ runner.os == 'Linux' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --service=github